routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\EtiquetaController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\PostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;

Route::group(['middleware' => 'verified'], function () {

    Route::get('', [HomeController::class, 'index'])->middleware('language');

    Route::resource('categoria', CategoriaController::class)->middleware('language');

    Route::resource('etiquetas', EtiquetaController::class)->middleware('language');

    Route::resource('posts', PostController::class)->middleware('language');

    Route::resource('users', UserController::class)->middleware('language');
});

routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogControlador;
use App\Mail\InfoSubMaileable;
use Illuminate\Support\Facades\Mail;



Route::get('/', [BlogControlador::class, 'home'])->middleware('language');

Route::get('/lista', [BlogControlador::class, 'lista'])->middleware('language');
Route::get('/lista/categoria/{categoria}', [BlogControlador::class, 'listaCategoria'])->middleware('language');

Route::get('/post/{post}', [BlogControlador::class, 'post'])->middleware('language');

Route::get('/subcripcion', function () {
    $correo = new InfoSubMaileable;

    Mail::to('zellsusj229@gmail.com')->send($correo);
    return "Mensaje Enviado";
});

Auth::routes(['verify' => 'true']);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $guarded = ['id','created_at','updated_at'];
    // Relacion 1:N

    public function users()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function categorias()
    {
        return $this->belongsTo(Categoria::class, 'categoria_id');
    }


    // Relacion M:N

    public function etiquetas()
    {
        return $this->belongsToMany(Etiqueta::class);
    }

    //Relacion polimorfica

    public function image()
    {
        return $this->morphOne(Imagen::class, 'imageable');
    }

}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use App\Models\Categoria;
use App\Models\Etiqueta;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::where('user_id', auth()->user()->id)->latest('id')->paginate(10);
        return view('admin.posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = Categoria::pluck('nombre', 'id');
        $etiquetas = Etiqueta::all();
        return view('admin.posts.create', compact('categorias','etiquetas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        
        $posts = Post::create($request->all());
        $url = Storage::put('', $request->file('file'));
        $posts->image()->create([
            'url' => $url
        ]);
        $posts->save();

        if ($request->etiquetas) {
            $posts->etiquetas()->sync($request->etiquetas);
        }
        
        $request->session()->flash('info-create','Post Creado');
        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categorias = Categoria::pluck('nombre', 'id');
        $etiquetas = Etiqueta::all();
        return view('admin.posts.edit', compact('post','categorias','etiquetas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        $post->update($request->all());
        // $url = Storage::put('', $request->file('file'));

        if ($request->file('file')) {
            $url = Storage::put('',$request->file('file'));
            if ($post->image) {
                Storage::delete($post->image->url);

                $post->image->update([
                    'url' => $url
                ]);
            }else{
                $post->image()->create([
                    'url' => $url
                ]);
                // $post->save();
            }
        }
        $post->save();
        $request->session()->flash('info-create','Post Actializado');
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Post $post)
    {
        $categorias = Post::find($post->id);
        $categorias->delete();
        $request->session()->flash('info-drop','Categoria Borrada');
        return redirect('admin/posts');
    }
}

resources/views/admin/posts/create.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Crear Post</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::open(['route' => 'posts.store', 'files'=> true]) !!}

            {!! Form::hidden('user_id', auth()->user()->id) !!}

            <div class="form-group">
                {!! Form::label('nombre', 'Nombre') !!}
                {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => 'Nombre del nueva Post']) !!}

                @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('slug', 'Slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug del nueva Post', 'readonly']) !!}

                @error('slug')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('categoria_id', 'Categorias') !!}
                {!! Form::select('categoria_id', $categorias, null, ['class' => 'form-control', 'placeholder' => 'Categoria del Post']) !!}

                @error('categoria_id')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="row mr-3">
                <div class="col">
                    <div class="image-warp">
                        <img id="picture" src="https://cdn.pixabay.com/photo/2021/02/21/18/48/elks-6037526_1280.jpg"
                            alt="Imagen">
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {!! Form::label('file', 'Imagen Portada') !!}
                        {!! Form::file('file', ['class' => 'form-control']) !!}
                        <h4>Requisistos de la imagen</h4>
                        <p>Para que la imagen se vea bien el la pagina debeta tener:</p>
                        <p>- El tamaño de la imangen debera ser de 1600 x 545, podria ser mas grande pero siguiendo la misma
                            estetica</p>
                        <p>- El peso de la imagen no puede ser superior a 5Mb</p>
                        <p>- Escoja una imagen adecuada para el Post </p>

                        @error('file')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

            </div>
            <div class="form-group">
                <p class="font-weight-bold">Etiquetas</p>

                @foreach ($etiquetas as $etiqueta)

                    <label class="mr-3">
                        {!! Form::checkbox('etiquetas[]', $etiqueta->id, null) !!}
                        {{ $etiqueta->nombre }}
                    </label>

                @endforeach

                @error('etiquetas')
                    <br>
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                <p class="font-weight-bold">Estado</p>

                <label class="mr-3">
                    {!! Form::radio('estado', 1, true) !!}
                    Borrador
                </label>
                <label class="mr-3">
                    {!! Form::radio('estado', 2) !!}
                    Publicado
                </label>

                @error('estado')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror

            </div>

            <div class="form-group">
                {!! Form::label('cuerpo', 'Cuerpo del Post') !!}
                {!! Form::textarea('cuerpo', null, ['class' => 'form-control']) !!}

                @error('cuerpo')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            {!! Form::submit('Crear Post', ['class' => 'btn btn-primary']) !!}

            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('css')
    <style>
        .image-warp {
            position: relative;
            padding-bottom: 56.25%
        }

        .image-warp img {
            position: absolute;
            object-fit: cover;
            width: 100%;
            height: 100%;
        }

    </style>
@stop
@section('js')
    <script src="{{ asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js') }}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
    <script>
        $(document).ready(function() {
            $("#nombre").stringToSlug({
                setEvents: 'keyup keydown blur',
                getPut: '#slug',
                space: '-'
            });
        });

        ClassicEditor
            .create(document.querySelector('#cuerpo'))
            .catch(error => {
                console.error(error);
            });

        //Cambiar imagen
        document.getElementById("file").addEventListener('change', cambiarImagen);

        function cambiarImagen(event) {
            var file = event.target.files[0];

            var reader = new FileReader();
            reader.onload = (event) => {
                document.getElementById("picture").setAttribute('src', event.target.result);
            };

            reader.readAsDataURL(file);
        }

    </script>
@stop

resources/views/admin/posts/edit.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Editando Post</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::model($post, ['route' => ['posts.update', $post->id], 'files' => true, 'method' => 'put']) !!}

            {!! Form::hidden('user_id', auth()->user()->id) !!}

            <div class="form-group">
                {!! Form::label('nombre', 'Nombre') !!}
                {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => 'Nombre del nueva Post']) !!}

                @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('slug', 'Slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug del nueva Post', 'readonly']) !!}

                @error('slug')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('categoria_id', 'Categorias') !!}
                {!! Form::select('categoria_id', $categorias, null, ['class' => 'form-control', 'placeholder' => 'Categoria del Post']) !!}

                @error('categoria_id')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="row mr-3">
                <div class="col">
                    <div class="image-warp">

                        @if ($post->image)
                            <img id="picture" src="{{ asset('storage/' . $post->image->url) }}"
                                alt="Imagen">
                        @else
                            <img id="picture" src="https://cdn.pixabay.com/photo/2021/02/21/18/48/elks-6037526_1280.jpg"
                                alt="Imagen">
                        @endif

                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        {!! Form::label('file', 'Imagen Portada') !!}
                        {!! Form::file('file', ['class' => 'form-control']) !!}
                        <h4>Requisistos de la imagen</h4>
                        <p>Para que la imagen se vea bien el la pagina debeta tener:</p>
                        <p>- El tamaño de la imangen debera se de 1600 x 545, podria ser mas grande pero siguiendo la misma
                            estetica</p>
                        <p>- El peso de la imagen no puede ser superior a 5Mb</p>
                        <p>- Escoja una imagen adecuada para el Post </p>

                        @error('file')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>

            </div>
            <div class="form-group">
                <p class="font-weight-bold">Etiquetas</p>

                @foreach ($etiquetas as $etiqueta)

                    <label class="mr-3">
                        {!! Form::checkbox('etiquetas[]', $etiqueta->id, null) !!}
                        {{ $etiqueta->nombre }}
                    </label>

                @endforeach

                @error('etiquetas')
                    <br>
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                <p class="font-weight-bold">Estado</p>

                <label class="mr-3">
                    {!! Form::radio('estado', 1, true) !!}
                    Borrador
                </label>
                <label class="mr-3">
                    {!! Form::radio('estado', 2) !!}
                    Publicado
                </label>

                @error('estado')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror

            </div>

            <div class="form-group">
                {!! Form::label('cuerpo', 'Cuerpo del Post') !!}
                {!! Form::textarea('cuerpo', null, ['class' => 'form-control']) !!}

                @error('cuerpo')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            {!! Form::submit('Actualizar Post', ['class' => 'btn btn-primary']) !!}

            {!! Form::close() !!}
        </div>
    </div>
@stop
@section('css')
    <style>
        .image-warp {
            position: relative;
            padding-bottom: 56.25%
        }

        .image-warp img {
            position: absolute;
            object-fit: cover;
            width: 100%;
            height: 100%;
        }

    </style>
@stop
@section('js')
    <script src="{{ asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js') }}"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
    <script>
        $(document).ready(function() {
            $("#nombre").stringToSlug({
                setEvents: 'keyup keydown blur',
                getPut: '#slug',
                space: '-'
            });
        });

        ClassicEditor
            .create(document.querySelector('#cuerpo'))
            .catch(error => {
                console.error(error);
            });

        //Cambiar imagen
        document.getElementById("file").addEventListener('change', cambiarImagen);

        function cambiarImagen(event) {
            var file = event.target.files[0];

            var reader = new FileReader();
            reader.onload = (event) => {
                document.getElementById("picture").setAttribute('src', event.target.result);
            };

            reader.readAsDataURL(file);
        }

    </script>
@stop

resources/views/admin/posts/index.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Lista Posts</h1>
@stop

@section('content')

    <div class="text-right">
        <a class="btn btn-success" href="{{ route('posts.create') }}">Crear Post</a>

    </div>
    <br>
    @if (Session::has('info-update'))
        <div class="alert alert-success">
            <strong>{{ Session::get('info-update') }}</strong>
        </div>
    @endif

    @if (Session::has('info-create'))
        <div class="alert alert-success">
            <strong>{{ Session::get('info-create') }}</strong>
        </div>
    @endif

    @if (Session::has('info-drop'))
        <div class="alert alert-danger">
            <strong>{{ Session::get('info-drop') }}</strong>
        </div>
    @endif

    <div class="card">
        <div class="card-body text-center">
            <table class="table table-striped text-center">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Autor</th>
                        <th>Categoria</th>
                        <th>Estado</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($posts as $post)

                        <tr>
                            <td>{{ $post->id }}</td>
                            <td>{{ $post->nombre }}</td>
                            <td>{{ $post->users->name }}</td>
                            <td>{{ $post->categorias->nombre }}</td>
                            <td>
                                @if ($post->estado == 1)
                                    Borrador
                                @else
                                    Publicado
                                @endif
                            </td>
                        </tr>
                        <tr colspan="5">
                            <td></td>
                            <td></td>
                            <td>
                                <a class="btn btn-info btn-sm" href="{{ route('posts.show', $post) }}">Show</a>

                            </td>
                            <td>
                                <a class="btn btn-primary btn-sm"
                                    href="{{ url('admin/posts/' . $post->id . '/edit') }}">Editar</a>

                            </td>
                            <td>
                                <form action="{{ route('posts.destroy', $post) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger btn-sm">Borrar</button>
                                </form>
                            </td>
                        </tr>

                    @endforeach

                </tbody>
                {{ $posts->links() }}
            </table>
        </div>
    </div>
@stop