routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\EtiquetaController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\PostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;

Route::group(['middleware' => 'verified'], function () {

    Route::get('', [HomeController::class, 'index'])->middleware('language');

    Route::resource('categoria', CategoriaController::class)->middleware('language');

    Route::resource('etiquetas', EtiquetaController::class)->middleware('language');

    Route::resource('posts', PostController::class)->middleware('language');

    Route::resource('users', UserController::class)->middleware('language');
});

routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogControlador;
use App\Mail\InfoSubMaileable;
use Illuminate\Support\Facades\Mail;



Route::get('/', [BlogControlador::class, 'home'])->middleware('language');

Route::get('/lista', [BlogControlador::class, 'lista'])->middleware('language');
Route::get('/lista/categoria/{categoria}', [BlogControlador::class, 'listaCategoria'])->middleware('language');

Route::get('/post/{post}', [BlogControlador::class, 'post'])->middleware('language');

Route::get('/subcripcion', function () {
    $correo = new InfoSubMaileable;

    Mail::to('zellsusj229@gmail.com')->send($correo);
    return "Mensaje Enviado";
});

Auth::routes(['verify' => 'true']);

app/Models/Categoria.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
    use HasFactory;

    protected $fillable = ['nombre','slug'];
    // Relacion 1:N
    
    public function posts()
    {
        return $this->hasMany(Post::class, 'categoria_id');
    }
}

app/Http/Controllers/Admin/CategoriaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Categoria;

class CategoriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categorias = Categoria::paginate(10);
        return view('admin.categorias.index', compact('categorias'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categorias.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required',
            'slug'=>'required|unique:categorias'
        ]);
        $categorias = Categoria::create($request->all());
        $categorias->save();
        $categorias = Categoria::all();
        $request->session()->flash('info-create','Categoria Creada');
        return redirect('admin/categoria');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Categoria $categorium)
    {
        return view('admin.categorias.show', compact('categorium'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Categoria $categorium)
    {
        return view('admin.categorias.edit', compact('categorium'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categoria $categorium)
    {
        $request->validate([
            'nombre'=>'required',
            'slug'=>"required|unique:categorias,slug,$categorium->id"
        ]);
        $categorium->update($request->all());
        $categorium->save();
        $categorium = Categoria::all();
        $categorias = $categorium;
        $request->session()->flash('info-update','Categoria Actualizada');
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Categoria $categorium)
    {
        $categorias = Categoria::find($categorium->id);
        $categorias->delete();
        $request->session()->flash('info-drop','Categoria Borrada');
        return redirect('admin/categoria');
    }
}

resources/views/admin/categorias/create.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Crear Categoria</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::open(['route' => 'categoria.store']) !!}
            <div class="form-group">
                {!! Form::label('nombre', 'Nombre') !!}
                {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => 'Nombre de la nueva Categoria']) !!}

                @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('slug', 'Slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug de la nueva Categoria', 'readonly']) !!}

                @error('slug')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            {!! Form::submit('Crear Categoria', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('js')
    <script src="{{ asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $("#nombre").stringToSlug({
                setEvents: 'keyup keydown blur',
                getPut: '#slug',
                space: '-'
            });
        });

    </script>
@stop

resources/views/admin/categorias/edit.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Editar Categoria</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::model($categorium, ['route' => ['categoria.update', $categorium->slug], 'method' => 'put']) !!}
            <div class="form-group">
                {!! Form::label('nombre', 'Nombre') !!}
                {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => 'Nombre de la nueva Categoria']) !!}

                @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('slug', 'Slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug de la nueva Categoria','readonly']) !!}

                @error('slug')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            {!! Form::submit('Actualizar Categoria', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script src="{{ asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $("#nombre").stringToSlug({
                setEvents: 'keyup keydown blur',
                getPut: '#slug',
                space: '-'
            });
        });

    </script>
@stop

resources/views/admin/categorias/index.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Lista De Categorias</h1>
@stop

@section('content')
    <div class="text-right">
        <a class="btn btn-success" href="{{ route('categoria.create') }}">Crear Categoria</a>

    </div>
    <br>
    @if (Session::has('info-update'))
        <div class="alert alert-success">
            <strong>{{ Session::get('info-update') }}</strong>
        </div>
    @endif

    @if (Session::has('info-create'))
        <div class="alert alert-success">
            <strong>{{ Session::get('info-create') }}</strong>
        </div>
    @endif

    @if (Session::has('info-drop'))
        <div class="alert alert-danger">
            <strong>{{ Session::get('info-drop') }}</strong>
        </div>
    @endif

    <div class="card">
        <div class="card-body">
            <table class="table table-striped text-center">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Slug</th>
                    </tr>
                </thead>

                <tbody>
                    @foreach ($categorias as $categoria)

                        <tr>
                            <td>{{ $categoria->id }}</td>
                            <td>{{ $categoria->nombre }}</td>
                            <td>{{ $categoria->slug }}</td>
                            <td width='10px'>
                                <a class="btn btn-info"
                                    href="{{ route('categoria.show', $categoria) }}">Show</a>
    
                            </td>
                            <td width='10px'>
                                <a class="btn btn-primary"
                                    href="{{ url('admin/categoria/' . $categoria->slug . '/edit') }}">Editar</a>

                            </td>
                            <td width='10px'>
                                <form action="{{ route('categoria.destroy', $categoria) }}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-danger">Borrar</button>
                                </form>
                            </td>
                        </tr>

                    @endforeach
                    
                </tbody>
                {{ $categorias->links() }}
            </table>
        </div>
    </div>

@stop

resources/views/admin/categorias/show.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Detalles</h1>
@stop

@section('content')
<div class="text-right">
    <a class="btn btn-success" href="{{ route('categoria.index') }}">Volver</a>

</div>
<br>
<div class="card">
    <div class="card-body">
        <h3>Categoria</h3>
        <br>
        <p> Id: {{$categorium->id}}</p>
        <p>Nombre: {{$categorium->nombre}}</p>
        <p>Slug: {{$categorium->slug}}</p>
    </div>
</div>
@stop