routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoriaController;
use App\Http\Controllers\Admin\EtiquetaController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\PostController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\UserController;

Route::group(['middleware' => 'verified'], function () {

    Route::get('', [HomeController::class, 'index'])->middleware('language');

    Route::resource('categoria', CategoriaController::class)->middleware('language');

    Route::resource('etiquetas', EtiquetaController::class)->middleware('language');

    Route::resource('posts', PostController::class)->middleware('language');

    Route::resource('users', UserController::class)->middleware('language');
});

routes/web.php
<?php


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BlogControlador;
use App\Mail\InfoSubMaileable;
use Illuminate\Support\Facades\Mail;



Route::get('/', [BlogControlador::class, 'home'])->middleware('language');

Route::get('/lista', [BlogControlador::class, 'lista'])->middleware('language');
Route::get('/lista/categoria/{categoria}', [BlogControlador::class, 'listaCategoria'])->middleware('language');

Route::get('/post/{post}', [BlogControlador::class, 'post'])->middleware('language');

Route::get('/subcripcion', function () {
    $correo = new InfoSubMaileable;

    Mail::to('zellsusj229@gmail.com')->send($correo);
    return "Mensaje Enviado";
});

Auth::routes(['verify' => 'true']);

app/Models/Etiqueta.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Etiqueta extends Model
{
    use HasFactory;
    protected $fillable = ['nombre','slug'];
    // Relacion M:N

    public function posts()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/Admin/EtiquetaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Etiqueta;
use Illuminate\Http\Request;

class EtiquetaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $etiquetas = Etiqueta::paginate(10);
        return view('admin.etiquetas.index', compact('etiquetas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.etiquetas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required',
            'slug'=>'required|unique:categorias'
        ]);
        $etiquetas = Etiqueta::create($request->all());
        $etiquetas->save();
        $etiquetas = Etiqueta::all();
        $request->session()->flash('info-create','Etiqueta Creada');
        return redirect('admin/etiquetas');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Etiqueta $etiqueta)
    {
        return view('admin.etiquetas.show', compact('etiqueta'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Etiqueta $etiqueta)
    {
        return view('admin.etiquetas.edit', compact('etiqueta'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Etiqueta $etiqueta)
    {
        $request->validate([
            'nombre'=>'required',
            'slug'=>"required|unique:categorias,slug,$etiqueta->id"
        ]);
        $etiqueta->update($request->all());
        $etiqueta->save();
        $etiqueta = Etiqueta::all();
        $etiquetas = $etiqueta;
        $request->session()->flash('info-update','Etiqueta Actualizada');
        return redirect('admin/etiquetas');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Etiqueta $etiqueta)
    {
        $etiquetas = Etiqueta::find($etiqueta->id);
        $etiquetas->delete();
        $request->session()->flash('info-drop','Etiqueta Borrada');
        return redirect('admin/etiquetas');
    }
}

resources/views/admin/etiquetas/create.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Crear Etiqueta</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::open(['route' => 'etiquetas.store']) !!}
            <div class="form-group">
                {!! Form::label('nombre', 'Nombre') !!}
                {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => 'Nombre de la nueva Etiqueta']) !!}

                @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('slug', 'Slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug de la nueva Etiqueta', 'readonly']) !!}

                @error('slug')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            {!! Form::submit('Crear Etiqueta', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('js')
    <script src="{{ asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $("#nombre").stringToSlug({
                setEvents: 'keyup keydown blur',
                getPut: '#slug',
                space: '-'
            });
        });

    </script>
@stop

resources/views/admin/etiquetas/edit.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Editar Etiqueta</h1>
@stop

@section('content')
    <div class="card">
        <div class="card-body">
            {!! Form::model($etiqueta, ['route' => ['etiquetas.update', $etiqueta->id], 'method' => 'put']) !!}
            <div class="form-group">
                {!! Form::label('nombre', 'Nombre') !!}
                {!! Form::text('nombre', null, ['class' => 'form-control', 'placeholder' => 'Nombre de la nueva Etiqueta']) !!}

                @error('nombre')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group">
                {!! Form::label('slug', 'Slug') !!}
                {!! Form::text('slug', null, ['class' => 'form-control', 'placeholder' => 'Slug de la nueva Etiqueta','readonly']) !!}

                @error('slug')
                    <span class="text-danger" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            {!! Form::submit('Actualizar Etiqueta', ['class' => 'btn btn-primary']) !!}
            {!! Form::close() !!}
        </div>
    </div>
@stop

@section('js')
    <script src="{{ asset('vendor/jQuery-Plugin-stringToSlug-1.3/jquery.stringToSlug.min.js') }}"></script>

    <script>
        $(document).ready(function() {
            $("#nombre").stringToSlug({
                setEvents: 'keyup keydown blur',
                getPut: '#slug',
                space: '-'
            });
        });

    </script>
@stop

resources/views/admin/etiquetas/index.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Lista Etiquetas</h1>
@stop

@section('content')
<div class="text-right">
    <a class="btn btn-success" href="{{ route('etiquetas.create') }}">Crear Etiqueta</a>

</div>
<br>
@if (Session::has('info-update'))
    <div class="alert alert-success">
        <strong>{{ Session::get('info-update') }}</strong>
    </div>
@endif

@if (Session::has('info-create'))
    <div class="alert alert-success">
        <strong>{{ Session::get('info-create') }}</strong>
    </div>
@endif

@if (Session::has('info-drop'))
    <div class="alert alert-danger">
        <strong>{{ Session::get('info-drop') }}</strong>
    </div>
@endif

<div class="card">
    <div class="card-body">
        <table class="table table-striped text-center">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nombre</th>
                </tr>
            </thead>

            <tbody>
                @foreach ($etiquetas as $etiqueta)

                    <tr>
                        <td>{{ $etiqueta->id }}</td>
                        <td>{{ $etiqueta->nombre }}</td>
                        <td width='10px'>
                            <a class="btn btn-info"
                                href="{{ route('etiquetas.show', $etiqueta) }}">Show</a>

                        </td>
                        <td width='10px'>
                            <a class="btn btn-primary"
                                href="{{ url('admin/etiquetas/' . $etiqueta->id . '/edit') }}">Editar</a>

                        </td>
                        <td width='10px'>
                            <form action="{{ route('etiquetas.destroy', $etiqueta) }}" method="post">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Borrar</button>
                            </form>
                        </td>
                    </tr>

                @endforeach
                
            </tbody>
            {{ $etiquetas->links() }}
        </table>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('js')
    <script> console.log('Hi!'); </script>
@stop

resources/views/admin/etiquetas/show.blade.php
@extends('adminlte::page')

@section('title', 'Un Libro Abierto')

@section('content_header')
    <h1>Detalles</h1>
@stop

@section('content')
<div class="text-right">
    <a class="btn btn-success" href="{{ route('etiquetas.index') }}">Volver</a>

</div>
<br>
<div class="card">
    <div class="card-body">
        <h3>Etiqueta</h3>
        <br>
        <p> Id: {{$etiqueta->id}}</p>
        <p>Nombre: {{$etiqueta->nombre}}</p>
        <p>Slug: {{$etiqueta->slug}}</p>
    </div>
</div>
@stop